version: '3'
services:
  flask-app:
    image:  rslim087/kubernetes-course-grade-submission-portal
    container_name: flask-app
    ports:
      - "8083:5001"
    environment:
      - GRADE_SERVICE_HOST=node-server
    depends_on:
      - node-server
    networks:
      - app-network

  node-server:
    image: rslim087/kubernetes-course-grade-submission-api:stateless
    container_name: node-server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge