version: '3.3'

services:
  ollama:
    container_name: ollama-service
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    networks:
      - default

  open-webui:
    container_name: open-webui-service
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "9003:8080"
    depends_on:
      - postgres
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL
      - WEBUI_SECRET_KEY
      - USE_CUDA_DOCKER
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - open_webui:/app/backend/data
    networks:
      - default

  postgres:
    container_name: postgres-service
    image: postgres:${PG_MAJOR:-15}
    environment:
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  ollama:
  open_webui:
  postgres: