version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8084:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8085:7860"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
